<map id="django.contrib.gis.gdal.error.OGRIndexError" name="django.contrib.gis.gdal.error.OGRIndexError">
<area shape="rect" id="node2" href="$d5/dec/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_o_g_r_exception.html" title="django.contrib.gis.gdal.error.\lOGRException" alt="" coords="5,80,192,121"/>
</map>
