<map id="Graphical Class Hierarchy" name="Graphical Class Hierarchy">
<area shape="rect" id="node2" href="$dc/d6d/classdjango_1_1db_1_1utils_1_1_error.html" title="django.db.utils.Error" alt="" coords="252,133,391,160"/>
<area shape="rect" id="node3" href="$da/def/classdjango_1_1db_1_1utils_1_1_database_error.html" title="django.db.utils.Database\lError" alt="" coords="611,155,777,197"/>
<area shape="rect" id="node10" href="$da/d3b/classdjango_1_1db_1_1utils_1_1_interface_error.html" title="django.db.utils.Interface\lError" alt="" coords="615,90,773,131"/>
<area shape="rect" id="node4" href="$de/d6e/classdjango_1_1db_1_1utils_1_1_data_error.html" title="django.db.utils.DataError" alt="" coords="913,5,1079,32"/>
<area shape="rect" id="node5" href="$d4/d07/classdjango_1_1db_1_1utils_1_1_integrity_error.html" title="django.db.utils.Integrity\lError" alt="" coords="918,57,1074,98"/>
<area shape="rect" id="node6" href="$db/d9f/classdjango_1_1db_1_1utils_1_1_internal_error.html" title="django.db.utils.Internal\lError" alt="" coords="920,122,1072,163"/>
<area shape="rect" id="node7" href="$d3/d64/classdjango_1_1db_1_1utils_1_1_not_supported_error.html" title="django.db.utils.NotSupported\lError" alt="" coords="901,187,1091,229"/>
<area shape="rect" id="node8" href="$da/dd3/classdjango_1_1db_1_1utils_1_1_operational_error.html" title="django.db.utils.Operational\lError" alt="" coords="908,253,1084,294"/>
<area shape="rect" id="node9" href="$da/d89/classdjango_1_1db_1_1utils_1_1_programming_error.html" title="django.db.utils.Programming\lError" alt="" coords="903,318,1089,359"/>
<area shape="rect" id="node12" href="$d9/d4a/classdjango_1_1contrib_1_1admin_1_1options_1_1_incorrect_lookup_parameters.html" title="django.contrib.admin.options.\lIncorrectLookupParameters" alt="" coords="225,577,417,618"/>
<area shape="rect" id="node13" href="$d7/d8c/classdjango_1_1contrib_1_1admin_1_1sites_1_1_already_registered.html" title="django.contrib.admin.sites.\lAlreadyRegistered" alt="" coords="232,642,411,683"/>
<area shape="rect" id="node14" href="$d6/daf/classdjango_1_1contrib_1_1admin_1_1sites_1_1_not_registered.html" title="django.contrib.admin.sites.\lNotRegistered" alt="" coords="232,707,411,749"/>
<area shape="rect" id="node15" href="$dc/d56/classdjango_1_1contrib_1_1admin_1_1util_1_1_not_relation_field.html" title="django.contrib.admin.util.\lNotRelationField" alt="" coords="238,773,405,814"/>
<area shape="rect" id="node16" href="$d2/da5/classdjango_1_1contrib_1_1auth_1_1models_1_1_site_profile_not_available.html" title="django.contrib.auth.models.\lSiteProfileNotAvailable" alt="" coords="230,838,413,879"/>
<area shape="rect" id="node17" href="$de/d7e/classdjango_1_1contrib_1_1comments_1_1moderation_1_1_already_moderated.html" title="django.contrib.comments.moderation.\lAlreadyModerated" alt="" coords="201,955,441,997"/>
<area shape="rect" id="node18" href="$dd/d40/classdjango_1_1contrib_1_1comments_1_1moderation_1_1_not_moderated.html" title="django.contrib.comments.moderation.\lNotModerated" alt="" coords="201,1021,441,1062"/>
<area shape="rect" id="node19" href="$d2/d32/classdjango_1_1contrib_1_1gis_1_1db_1_1backends_1_1postgis_1_1introspection_1_1_geo_introspection_error.html" title="django.contrib.gis.db.backends.postgis.introspection.\lGeoIntrospectionError" alt="" coords="156,1086,487,1127"/>
<area shape="rect" id="node20" href="$d4/dd5/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_g_d_a_l_exception.html" title="OGR &amp; SRS Exceptions ####. " alt="" coords="228,1151,415,1193"/>
<area shape="rect" id="node21" href="$d5/dec/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_o_g_r_exception.html" title="django.contrib.gis.gdal.error.\lOGRException" alt="" coords="228,1217,415,1258"/>
<area shape="rect" id="node23" href="$d9/d14/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_s_r_s_exception.html" title="django.contrib.gis.gdal.error.\lSRSException" alt="" coords="228,1347,415,1389"/>
<area shape="rect" id="node24" href="$da/d02/classdjango_1_1contrib_1_1gis_1_1geoip_1_1base_1_1_geo_i_p_exception.html" title="GeoIP classes ####. " alt="" coords="224,1413,419,1454"/>
<area shape="rect" id="node25" href="$d0/d8c/classdjango_1_1contrib_1_1gis_1_1geos_1_1error_1_1_g_e_o_s_exception.html" title="django.contrib.gis.geos.error.\lGEOSException" alt="" coords="226,1282,417,1323"/>
<area shape="rect" id="node27" href="$d5/d5b/classdjango_1_1contrib_1_1gis_1_1maps_1_1google_1_1gmap_1_1_google_map_exception.html" title="django.contrib.gis.maps.google.gmap.\lGoogleMapException" alt="" coords="200,1478,443,1519"/>
<area shape="rect" id="node28" href="$d3/d2a/classdjango_1_1contrib_1_1gis_1_1utils_1_1layermapping_1_1_layer_map_error.html" title="django.contrib.gis.utils.layermapping.\lLayerMapError" alt="" coords="203,1543,440,1585"/>
<area shape="rect" id="node33" href="$d1/db2/classdjango_1_1contrib_1_1messages_1_1api_1_1_message_failure.html" title="django.contrib.messages.api.\lMessageFailure" alt="" coords="225,1609,417,1650"/>
<area shape="rect" id="node34" href="$d7/d20/classdjango_1_1contrib_1_1sessions_1_1backends_1_1base_1_1_create_error.html" title="django.contrib.sessions.backends.base.\lCreateError" alt="" coords="194,1674,449,1715"/>
<area shape="rect" id="node35" href="$d6/de3/classdjango_1_1contrib_1_1sitemaps_1_1_sitemap_not_found.html" title="django.contrib.sitemaps.\lSitemapNotFound" alt="" coords="239,1739,403,1781"/>
<area shape="rect" id="node36" href="$d9/d05/classdjango_1_1core_1_1exceptions_1_1_field_error.html" title="django.core.exceptions.Field\lError" alt="" coords="227,1805,415,1846"/>
<area shape="rect" id="node37" href="$d6/d19/classdjango_1_1core_1_1exceptions_1_1_improperly_configured.html" title="django.core.exceptions.Improperly\lConfigured" alt="" coords="211,1870,431,1911"/>
<area shape="rect" id="node41" href="$d3/d47/classdjango_1_1core_1_1exceptions_1_1_middleware_not_used.html" title="django.core.exceptions.Middleware\lNotUsed" alt="" coords="209,1935,434,1977"/>
<area shape="rect" id="node42" href="$d5/d0c/classdjango_1_1core_1_1exceptions_1_1_multiple_objects_returned.html" title="django.core.exceptions.Multiple\lObjectsReturned" alt="" coords="219,2001,424,2042"/>
<area shape="rect" id="node43" href="$d8/d04/classdjango_1_1core_1_1exceptions_1_1_object_does_not_exist.html" title="django.core.exceptions.Object\lDoesNotExist" alt="" coords="222,2066,421,2107"/>
<area shape="rect" id="node45" href="$db/d76/classdjango_1_1core_1_1exceptions_1_1_permission_denied.html" title="django.core.exceptions.Permission\lDenied" alt="" coords="209,2131,434,2173"/>
<area shape="rect" id="node46" href="$d9/d60/classdjango_1_1core_1_1exceptions_1_1_suspicious_operation.html" title="django.core.exceptions.Suspicious\lOperation" alt="" coords="209,2197,433,2238"/>
<area shape="rect" id="node56" href="$d0/d31/classdjango_1_1core_1_1exceptions_1_1_validation_error.html" title="django.core.exceptions.Validation\lError" alt="" coords="213,2262,430,2303"/>
<area shape="rect" id="node57" href="$d7/dff/classdjango_1_1core_1_1exceptions_1_1_view_does_not_exist.html" title="django.core.exceptions.View\lDoesNotExist" alt="" coords="227,2327,415,2369"/>
<area shape="rect" id="node58" href="$d0/dd7/classdjango_1_1core_1_1files_1_1uploadhandler_1_1_upload_file_exception.html" title="django.core.files.uploadhandler.\lUploadFileException" alt="" coords="219,2393,423,2434"/>
<area shape="rect" id="node62" href="$dc/d17/classdjango_1_1core_1_1management_1_1base_1_1_command_error.html" title="django.core.management.base.\lCommandError" alt="" coords="219,2458,423,2499"/>
<area shape="rect" id="node63" href="$d1/d20/classdjango_1_1core_1_1paginator_1_1_invalid_page.html" title="django.core.paginator.InvalidPage" alt="" coords="214,2524,429,2551"/>
<area shape="rect" id="node66" href="$dd/d95/classdjango_1_1core_1_1serializers_1_1base_1_1_deserialization_error.html" title="django.core.serializers.base.\lDeserializationError" alt="" coords="227,2575,415,2617"/>
<area shape="rect" id="node67" href="$d3/d43/classdjango_1_1core_1_1serializers_1_1base_1_1_serialization_error.html" title="django.core.serializers.base.\lSerializationError" alt="" coords="227,2641,415,2682"/>
<area shape="rect" id="node68" href="$d6/dcc/classdjango_1_1core_1_1signing_1_1_bad_signature.html" title="django.core.signing.BadSignature" alt="" coords="213,2707,429,2733"/>
<area shape="rect" id="node70" href="$d8/d53/classdjango_1_1core_1_1urlresolvers_1_1_no_reverse_match.html" title="django.core.urlresolvers.\lNoReverseMatch" alt="" coords="240,2758,403,2799"/>
<area shape="rect" id="node71" href="$d9/da9/classdjango_1_1db_1_1backends_1_1dummy_1_1base_1_1_database_error.html" title="django.db.backends.dummy.base.\lDatabaseError" alt="" coords="211,2823,432,2865"/>
<area shape="rect" id="node73" href="$d2/dd2/classdjango_1_1db_1_1models_1_1fields_1_1_field_does_not_exist.html" title="django.db.models.fields.\lFieldDoesNotExist" alt="" coords="240,2889,403,2930"/>
<area shape="rect" id="node74" href="$d5/d38/classdjango_1_1db_1_1models_1_1loading_1_1_unavailable_app.html" title="django.db.models.loading.\lUnavailableApp" alt="" coords="235,2954,408,2995"/>
<area shape="rect" id="node75" href="$d7/d27/classdjango_1_1db_1_1models_1_1query__utils_1_1_invalid_query.html" title="django.db.models.query\l_utils.InvalidQuery" alt="" coords="241,3019,401,3061"/>
<area shape="rect" id="node76" href="$d3/d0f/classdjango_1_1db_1_1models_1_1sql_1_1datastructures_1_1_empty_result_set.html" title="django.db.models.sql.datastructures.\lEmptyResultSet" alt="" coords="203,3085,439,3126"/>
<area shape="rect" id="node77" href="$d1/d5b/classdjango_1_1db_1_1models_1_1sql_1_1datastructures_1_1_multi_join.html" title="django.db.models.sql.datastructures.\lMultiJoin" alt="" coords="203,3150,439,3191"/>
<area shape="rect" id="node78" href="$d8/dd8/classdjango_1_1db_1_1models_1_1sql_1_1where_1_1_empty_short_circuit.html" title="django.db.models.sql.where.\lEmptyShortCircuit" alt="" coords="228,3215,415,3257"/>
<area shape="rect" id="node79" href="$db/d21/classdjango_1_1db_1_1utils_1_1_connection_does_not_exist.html" title="django.db.utils.Connection\lDoesNotExist" alt="" coords="234,3281,409,3322"/>
<area shape="rect" id="node80" href="$dd/d97/classdjango_1_1http_1_1multipartparser_1_1_input_stream_exhausted.html" title="django.http.multipartparser.\lInputStreamExhausted" alt="" coords="231,3346,411,3387"/>
<area shape="rect" id="node81" href="$d0/d65/classdjango_1_1http_1_1multipartparser_1_1_multi_part_parser_error.html" title="django.http.multipartparser.\lMultiPartParserError" alt="" coords="231,3411,411,3453"/>
<area shape="rect" id="node82" href="$d3/d34/classdjango_1_1http_1_1response_1_1_http404.html" title="django.http.response.Http404" alt="" coords="225,3477,417,3504"/>
<area shape="rect" id="node83" href="$d5/da7/classdjango_1_1template_1_1base_1_1_invalid_template_library.html" title="django.template.base.Invalid\lTemplateLibrary" alt="" coords="229,3529,414,3570"/>
<area shape="rect" id="node84" href="$d6/d30/classdjango_1_1template_1_1base_1_1_template_does_not_exist.html" title="django.template.base.Template\lDoesNotExist" alt="" coords="220,3594,423,3635"/>
<area shape="rect" id="node85" href="$da/d7d/classdjango_1_1template_1_1base_1_1_template_encoding_error.html" title="django.template.base.Template\lEncodingError" alt="" coords="220,3659,423,3701"/>
<area shape="rect" id="node86" href="$db/dd8/classdjango_1_1template_1_1base_1_1_template_syntax_error.html" title="django.template.base.Template\lSyntaxError" alt="" coords="220,3725,423,3766"/>
<area shape="rect" id="node87" href="$df/d5b/classdjango_1_1template_1_1base_1_1_variable_does_not_exist.html" title="django.template.base.Variable\lDoesNotExist" alt="" coords="223,3790,420,3831"/>
<area shape="rect" id="node88" href="$d3/d19/classdjango_1_1template_1_1context_1_1_context_pop_exception.html" title="django.template.context.\lContextPopException" alt="" coords="239,3855,404,3897"/>
<area shape="rect" id="node89" href="$d1/d71/classdjango_1_1template_1_1loader__tags_1_1_extends_error.html" title="django.template.loader\l_tags.ExtendsError" alt="" coords="245,3921,398,3962"/>
<area shape="rect" id="node90" href="$d7/d38/classdjango_1_1template_1_1response_1_1_content_not_rendered_error.html" title="django.template.response.\lContentNotRenderedError" alt="" coords="234,3986,409,4027"/>
<area shape="rect" id="node91" href="$d7/d91/classdjango_1_1test_1_1__doctest_1_1_doc_test_failure.html" title="django.test._doctest.Doc\lTestFailure" alt="" coords="238,4051,405,4093"/>
<area shape="rect" id="node92" href="$df/d20/classdjango_1_1test_1_1__doctest_1_1_unexpected_exception.html" title="django.test._doctest.Unexpected\lException" alt="" coords="215,4117,428,4158"/>
<area shape="rect" id="node93" href="$dd/d3a/classdjango_1_1utils_1_1__os_1_1_windows_error.html" title="django.utils._os.Windows\lError" alt="" coords="236,185,407,226"/>
<area shape="rect" id="node94" href="$d6/ddd/classdjango_1_1utils_1_1archive_1_1_archive_exception.html" title="django.utils.archive.Archive\lException" alt="" coords="232,250,411,291"/>
<area shape="rect" id="node96" href="$d5/d97/classdjango_1_1utils_1_1unittest_1_1case_1_1___expected_failure.html" title="django.utils.unittest.case.\l_ExpectedFailure" alt="" coords="236,315,407,357"/>
<area shape="rect" id="node97" href="$dc/d8a/classdjango_1_1utils_1_1unittest_1_1case_1_1___unexpected_success.html" title="django.utils.unittest.case.\l_UnexpectedSuccess" alt="" coords="236,381,407,422"/>
<area shape="rect" id="node98" href="$dd/d13/classdjango_1_1utils_1_1unittest_1_1case_1_1_skip_test.html" title="django.utils.unittest.case.\lSkipTest" alt="" coords="236,446,407,487"/>
<area shape="rect" id="node99" href="$dc/dbf/classdjango_1_1views_1_1generic_1_1_generic_view_error.html" title="django.views.generic.Generic\lViewError" alt="" coords="226,511,417,553"/>
<area shape="rect" id="node22" href="$db/d65/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_o_g_r_index_error.html" title="django.contrib.gis.gdal.error.\lOGRIndexError" alt="" coords="601,1090,787,1131"/>
<area shape="rect" id="node26" href="$d3/d64/classdjango_1_1contrib_1_1gis_1_1geos_1_1error_1_1_g_e_o_s_index_error.html" title="django.contrib.gis.geos.error.\lGEOSIndexError" alt="" coords="599,1219,789,1261"/>
<area shape="rect" id="node29" href="$d7/d1e/classdjango_1_1contrib_1_1gis_1_1utils_1_1layermapping_1_1_invalid_decimal.html" title="django.contrib.gis.utils.layermapping.\lInvalidDecimal" alt="" coords="575,1381,813,1422"/>
<area shape="rect" id="node30" href="$d8/dfe/classdjango_1_1contrib_1_1gis_1_1utils_1_1layermapping_1_1_invalid_integer.html" title="django.contrib.gis.utils.layermapping.\lInvalidInteger" alt="" coords="575,1446,813,1487"/>
<area shape="rect" id="node31" href="$d8/dde/classdjango_1_1contrib_1_1gis_1_1utils_1_1layermapping_1_1_invalid_string.html" title="django.contrib.gis.utils.layermapping.\lInvalidString" alt="" coords="575,1511,813,1553"/>
<area shape="rect" id="node32" href="$d7/d87/classdjango_1_1contrib_1_1gis_1_1utils_1_1layermapping_1_1_missing_foreign_key.html" title="django.contrib.gis.utils.layermapping.\lMissingForeignKey" alt="" coords="575,1577,813,1618"/>
<area shape="rect" id="node38" href="$d5/d9b/classdjango_1_1contrib_1_1formtools_1_1wizard_1_1storage_1_1exceptions_1_1_missing_storage.html" title="django.contrib.formtools.wizard.storage.exceptions.\lMissingStorage" alt="" coords="535,1773,853,1814"/>
<area shape="rect" id="node39" href="$d9/da9/classdjango_1_1contrib_1_1formtools_1_1wizard_1_1storage_1_1exceptions_1_1_no_file_storage_configured.html" title="django.contrib.formtools.wizard.storage.exceptions.\lNoFileStorageConfigured" alt="" coords="535,1642,853,1683"/>
<area shape="rect" id="node40" href="$dd/d9f/classdjango_1_1core_1_1cache_1_1backends_1_1base_1_1_invalid_cache_backend_error.html" title="django.core.cache.backends.base.\lInvalidCacheBackendError" alt="" coords="582,1707,806,1749"/>
<area shape="rect" id="node44" href="$dd/d68/classdjango_1_1contrib_1_1syndication_1_1views_1_1_feed_does_not_exist.html" title="django.contrib.syndication.views.\lFeedDoesNotExist" alt="" coords="588,1838,800,1879"/>
<area shape="rect" id="node47" href="$d5/dd8/classdjango_1_1contrib_1_1admin_1_1exceptions_1_1_disallowed_model_admin_lookup.html" title="django.contrib.admin.exceptions.\lDisallowedModelAdminLookup" alt="" coords="587,2034,801,2075"/>
<area shape="rect" id="node48" href="$d9/d8a/classdjango_1_1contrib_1_1admin_1_1exceptions_1_1_disallowed_model_admin_to_field.html" title="django.contrib.admin.exceptions.\lDisallowedModelAdminToField" alt="" coords="587,2099,801,2141"/>
<area shape="rect" id="node49" href="$d4/d02/classdjango_1_1contrib_1_1formtools_1_1exceptions_1_1_wizard_view_cookie_modified.html" title="django.contrib.formtools.exceptions.\lWizardViewCookieModified" alt="" coords="579,2165,809,2206"/>
<area shape="rect" id="node50" href="$da/d7b/classdjango_1_1contrib_1_1sessions_1_1exceptions_1_1_invalid_session_key.html" title="django.contrib.sessions.exceptions.\lInvalidSessionKey" alt="" coords="579,2230,809,2271"/>
<area shape="rect" id="node51" href="$db/d60/classdjango_1_1contrib_1_1sessions_1_1exceptions_1_1_suspicious_session.html" title="django.contrib.sessions.exceptions.\lSuspiciousSession" alt="" coords="579,2295,809,2337"/>
<area shape="rect" id="node52" href="$dd/d4c/classdjango_1_1core_1_1exceptions_1_1_disallowed_host.html" title="django.core.exceptions.DisallowedHost" alt="" coords="569,2361,819,2388"/>
<area shape="rect" id="node53" href="$df/d26/classdjango_1_1core_1_1exceptions_1_1_disallowed_redirect.html" title="django.core.exceptions.Disallowed\lRedirect" alt="" coords="583,2413,805,2454"/>
<area shape="rect" id="node54" href="$d8/dfa/classdjango_1_1core_1_1exceptions_1_1_suspicious_file_operation.html" title="django.core.exceptions.Suspicious\lFileOperation" alt="" coords="582,1903,806,1945"/>
<area shape="rect" id="node55" href="$db/da8/classdjango_1_1core_1_1exceptions_1_1_suspicious_multipart_form.html" title="django.core.exceptions.Suspicious\lMultipartForm" alt="" coords="582,1969,806,2010"/>
<area shape="rect" id="node59" href="$dd/da9/classdjango_1_1core_1_1files_1_1uploadhandler_1_1_skip_file.html" title="django.core.files.uploadhandler.\lSkipFile" alt="" coords="592,2609,796,2650"/>
<area shape="rect" id="node60" href="$d6/db7/classdjango_1_1core_1_1files_1_1uploadhandler_1_1_stop_future_handlers.html" title="django.core.files.uploadhandler.\lStopFutureHandlers" alt="" coords="592,2478,796,2519"/>
<area shape="rect" id="node61" href="$dd/d60/classdjango_1_1core_1_1files_1_1uploadhandler_1_1_stop_upload.html" title="django.core.files.uploadhandler.\lStopUpload" alt="" coords="592,2543,796,2585"/>
<area shape="rect" id="node64" href="$d5/d1f/classdjango_1_1core_1_1paginator_1_1_empty_page.html" title="django.core.paginator.EmptyPage" alt="" coords="585,2675,803,2701"/>
<area shape="rect" id="node65" href="$d4/d7e/classdjango_1_1core_1_1paginator_1_1_page_not_an_integer.html" title="django.core.paginator.Page\lNotAnInteger" alt="" coords="604,2726,784,2767"/>
<area shape="rect" id="node69" href="$d8/d79/classdjango_1_1core_1_1signing_1_1_signature_expired.html" title="django.core.signing.Signature\lExpired" alt="" coords="597,2791,791,2833"/>
<area shape="rect" id="node72" href="$d7/dae/classdjango_1_1db_1_1backends_1_1dummy_1_1base_1_1_integrity_error.html" title="django.db.backends.dummy.base.\lIntegrityError" alt="" coords="583,2857,805,2898"/>
<area shape="rect" id="node95" href="$df/d12/classdjango_1_1utils_1_1archive_1_1_unrecognized_archive_format.html" title="django.utils.archive.Unrecognized\lArchiveFormat" alt="" coords="587,250,801,291"/>
<area shape="rect" id="node102" href="$d5/da6/classdjango_1_1core_1_1serializers_1_1base_1_1_serializer_does_not_exist.html" title="django.core.serializers.base.\lSerializerDoesNotExist" alt="" coords="600,865,788,906"/>
<area shape="rect" id="node103" href="$d7/daf/classdjango_1_1utils_1_1datastructures_1_1_multi_value_dict_key_error.html" title="django.utils.datastructures.\lMultiValueDictKeyError" alt="" coords="605,930,783,971"/>
</map>
