<map id="django.contrib.gis.geoip.base.GeoIPException" name="django.contrib.gis.geoip.base.GeoIPException">
</map>
