<map id="django.contrib.gis.gdal.error.OGRException" name="django.contrib.gis.gdal.error.OGRException">
</map>
