<map id="django.contrib.auth.tests.test_views.AuthViewsTestCase.assertFormError" name="django.contrib.auth.tests.test_views.AuthViewsTestCase.assertFormError">
<area shape="rect" id="node2" href="$db/d2b/classdjango_1_1contrib_1_1auth_1_1tests_1_1test__views_1_1_change_password_test.html#a14294d623686aa577993ba0d0bdf4b3d" title="django.contrib.auth.tests.test\l_views.ChangePasswordTest.fail_login" alt="" coords="345,13,589,54"/>
<area shape="rect" id="node4" href="$d7/daa/classdjango_1_1contrib_1_1auth_1_1tests_1_1test__views_1_1_password_reset_test.html#af3f338833b976f031c3283e0e7127d0b" title="django.contrib.auth.tests.test\l_views.PasswordResetTest.test\l_confirm_different_passwords" alt="" coords="364,77,571,133"/>
<area shape="rect" id="node5" href="$db/d2b/classdjango_1_1contrib_1_1auth_1_1tests_1_1test__views_1_1_change_password_test.html#a8d3050cd8fe79b4c8a343a88f5869729" title="django.contrib.auth.tests.test\l_views.ChangePasswordTest.test\l_password_change_fails_with_invalid\l_old_password" alt="" coords="350,158,585,229"/>
<area shape="rect" id="node6" href="$db/d2b/classdjango_1_1contrib_1_1auth_1_1tests_1_1test__views_1_1_change_password_test.html#aa7c764bc68bcbed136fb74517037bb07" title="django.contrib.auth.tests.test\l_views.ChangePasswordTest.test\l_password_change_fails_with_mismatched\l_passwords" alt="" coords="332,253,603,323"/>
<area shape="rect" id="node3" href="$db/d2b/classdjango_1_1contrib_1_1auth_1_1tests_1_1test__views_1_1_change_password_test.html#a06d40be6ca767f9bec30b65ff5bd8be5" title="django.contrib.auth.tests.test\l_views.ChangePasswordTest.test\l_password_change_succeeds" alt="" coords="651,5,867,61"/>
</map>
