<map id="django.contrib.gis.gdal.prototypes.errcheck.check_geom_offset" name="django.contrib.gis.gdal.prototypes.errcheck.check_geom_offset">
<area shape="rect" id="node2" href="$d8/d96/namespacedjango_1_1contrib_1_1gis_1_1gdal_1_1error.html#a36fdcad2a8f3ecafb144b30b9eae9424" title="django.contrib.gis.gdal.error.check_err" alt="" coords="417,5,660,32"/>
<area shape="rect" id="node3" href="$d6/d64/namespacedjango_1_1contrib_1_1gis_1_1gdal_1_1prototypes_1_1errcheck.html#ade2114e86912394953cebe6bef05d127" title="Geometry error&#45;checking routines ###. " alt="" coords="364,56,713,83"/>
<area shape="rect" id="node4" href="$d6/d64/namespacedjango_1_1contrib_1_1gis_1_1gdal_1_1prototypes_1_1errcheck.html#a95f78b184f48b5c887f94bf77124b076" title="django.contrib.gis.gdal.prototypes.errcheck.ptr\l_byref" alt="" coords="393,107,684,149"/>
</map>
