<map id="django.contrib.gis.geos.prototypes.errcheck.last_arg_byref" name="django.contrib.gis.geos.prototypes.errcheck.last_arg_byref">
<area shape="rect" id="node2" href="$d6/d5c/namespacedjango_1_1contrib_1_1gis_1_1geos_1_1prototypes_1_1coordseq.html#a3c3f31f3c17c91d0fd9423db84e43cb1" title="django.contrib.gis.geos.prototypes.coordseq.check\l_cs_get" alt="" coords="364,5,681,47"/>
<area shape="rect" id="node3" href="$d6/d69/namespacedjango_1_1contrib_1_1gis_1_1geos_1_1prototypes_1_1errcheck.html#a8fc6b2e34403f3218efe6b4b225b60ff" title="django.contrib.gis.geos.prototypes.errcheck.check_dbl" alt="" coords="353,71,692,98"/>
<area shape="rect" id="node4" href="$d6/d69/namespacedjango_1_1contrib_1_1gis_1_1geos_1_1prototypes_1_1errcheck.html#a67d3161b5f084b9eac4cd2ba6748e7c5" title="django.contrib.gis.geos.prototypes.errcheck.check\l_sized_string" alt="" coords="365,123,680,164"/>
</map>
